Map<String, List<String>> categories = {
  "Bebek ve Çocuk": [
    "Bebek Bezi",
    "Külot Bez",
    "Bebek Islak Havlu ve Mendil",
    "Bebek Mama",
    "Bebek Şampuanı",
    "Bebek Gereçleri",
    "Bebek Deterjan ve Yumuşatıcısı",
    "Bebek Bakım Ürünleri",
    "Bebek, Çocuk Giyim ve Tekstil",
    "Oyuncak",
    "Çocuk Kitapları",
    "Diğer",
  ],
  "Abur Cubur": [
    "Cips",
    "Kuruyemiş",
    "Çikolata",
    "Draje",
    "Gofret",
    "Bisküvi",
    "Kraker ve Tuzlu Bisküvi",
    "Kek",
    "İkramlık Ürünler",
    "Şekerleme",
    "Sakız",
    "Light Ürünler ve Protein Bar",
    "Diğer",
  ],
  "Dondurma": [
    "Tek Dondurma",
    "Kap Dondurma",
    "Çoklu Paket",
    "Buz",
    "Diğer",
  ],
  "Dondurulmuş Ürünler": [
    "Dondurulmuş Et Ürünleri",
    "Dondurulmuş Pizzalar",
    "Dondurulmuş Hamur İşleri",
    "Dondurulmuş Pasta ve Tatlı",
    "Dondurulmuş Sebzeler",
    "Dondurulmuş Deniz Ürünleri",
    "Diğer",
  ],
  "Elektronik": [
    "Beyaz Eşya",
    "Telefon ve Aksesuarları",
    "Bilgisayar ve Aksesuarları",
    "Elektrikli Küçük Ev Aletleri",
    "Elektrikli Kişisel Bakım",
    "Isıtma ve Soğutma",
    "Pil",
    "Ampul ve Aydınlatma",
    "Kablo, Priz ve Adaptör",
    "Digital Ürünler",
    "Diğer",
  ],
  "Ev ve Yaşam": [
    "Ev Tekstili",
    "Ev ve Ofis Mobilya",
    "Mutfak Gereçleri",
    "Banyo Gereçleri",
    "Dekorasyon",
    "Spor Ürünleri",
    "Hırdavat",
    "Ev Gereçleri",
    "Okul ve Kırtasiye",
    "Kitap ve Dergi",
    "Dış Mekan Mobilya",
    "Bahçe ve Çiçek",
    "Kamp ve Piknik",
    "Çöp Torbası, Streç ve Folyo",
    "Oto Aksesuar",
    "Parti Malzemeleri",
    "Tatil ve Deniz",
    "Diğer",
  ],
  "Evcil Hayvan": [
    "Kedi Maması",
    "Köpek Maması",
    "Pet Aksesuarları",
    "Diğer Mama",
    "Kedi Kumu ve Poşet",
    "Diğer",
  ],
  "Ekmek ve Pastane": [
    "Ekmek",
    "Fırından Sıcak",
    "Unlu Mamüller",
    "Paketli Ekmekler",
    "Hamur ve Pasta Malzemeleri",
    "Katmer, Lavaş ve Bazlama",
    "Kurabiye, Kuruvasan, Simit",
    "Galeta ve Grissini",
    "Diğer",
  ],
  "Et": [
    "Beyaz Et",
    "Paketli Beyaz Et",
    "Kırmızı Et",
    "Yumurta",
    "Sucuk",
    "Salam",
    "Sosis",
    "Kavurma",
    "Füme Ürünler",
    "Pastırma",
    "Jambon Ürünleri",
    "Diğer",
  ],
  "Giyim": [
    "Giyim",
    "Ayakkabı ve Bot",
    "Terlik",
    "Aksesuar",
    "Çorap",
    "Çanta ve Valiz",
    "İç Giyim",
    "Diğer",
  ],
  "İçecek": [
    "Su",
    "Maden Suyu",
    "Meyve Suyu",
    "Kola",
    "Gazoz",
    "Çay",
    "Kahve",
    "Enerji İçeceği",
    "Ayran",
    "Kefir",
    "Fonksiyonel İçecekler",
    "Boza ve Malt İçecekler",
    "Limonata, Şalgam ve Şerbet",
    "Salep ve Sıcak Çikolata",
    "Soğuk Çay",
    "Soğuk Kahve",
    "Soğuk Toz İçecekler",
    "Granül İçecek",
    "Diğer",
  ],
  "Kağıt Ürünler": [
    "Tuvalet Kağıdı",
    "Peçete",
    "Kağıt Havlu",
    "Kağıt Mendil",
    "Hijyenik Ped",
    "Temizlik Havlusu",
    "Diğer",
  ],
  "Kahvaltılık": [
    "Yumurta",
    "Zeytin",
    "Beyaz Peynir",
    "Kaşar Peynir",
    "Yöresel Peynir",
    "Çay",
    "Kahve",
    "Süt",
    "Reçel",
    "Bal",
    "Tahin, Pekmez ve Helva",
    "Krem Çikolata ve Ezme",
    "Sucuk",
    "Salam",
    "Sosis",
    "Kavurma",
    "Pastırma",
    "Kahvaltılık Gevrek",
    "Kahvaltılık Soslar",
    "Diğer",
  ],
  "Kişisel Bakım ve Kozmetik": [
    "Şampuan",
    "Banyo ve Sabun",
    "Yüz, Vücut, El Bakım ve Krem",
    "Makyaj",
    "Erkek Bakım ve Tıraş",
    "Ağız Bakım",
    "Saç Bakım",
    "Saç Boyası",
    "Saç Şekillendirici",
    "Deodorant ve Parfüm",
    "Kolonya",
    "Hijyenik Ped",
    "Epilasyon ve Ağda",
    "Sağlık Ürünleri",
    "Güneş Kremleri",
    "Diğer",
  ],
  "Meyve ve Sebze": [
    "Patates, Soğan, Sarımsak",
    "Meyve",
    "Narenciye",
    "Sebze",
    "Yeşillikler ve Otlar",
    "Kurutulmuş Meyve ve Sebze",
    "Kabuklu Sert Meyveler",
    "Hurmalar",
    "Diğer",
  ],
  "Oyuncak": [
    "Kutu Oyunları",
    "Oyuncak Bebek",
    "Peluş",
    "Yapı Oyuncakları",
    "Eğitici Oyuncaklar",
    "Oyun Hamuru",
    "Figür Oyuncak",
    "Oyuncak Araçlar",
    "Açık Hava, Deniz, Spor",
    "Kız Çocuk Oyun Setleri",
    "Erkek Çocuk Oyun Setleri",
    "Bebek Oyuncağı",
    "Robot",
    "Diğer",
  ],
  "Süt ve Süt Ürünleri": [
    "Süt",
    "Beyaz Peynir",
    "Yöresel Peynir",
    "Kaşar Peynir",
    "Yoğurt",
    "Tereyağ",
    "Krem Peynir",
    "Kaymak ve Krema",
    "Ayran",
    "Çocuk Ürünleri",
    "Kefir",
    "Maya",
    "Tatlı ve Puding",
    "Diğer",
  ],
  "Temizlik": [
    "Çamaşır",
    "Bulaşık",
    "Çamaşır Suyu",
    "Ev ve Yüzey Temizleyicileri",
    "Genel Temizlik Malzemeleri",
    "Temizlik Havlusu",
    "Banyo ve Sabun",
    "Oda Kokuları",
    "Ayakkabı Bakım",
    "Haşere Kovar",
    "Temizlik Bezleri",
    "Diğer",
  ],
  "Yemeklik Malzeme": [
    "Mutfak Şeker",
    "Un",
    "Sıvı Yağlar",
    "Pirinç ve Bulgur",
    "Bakliyat",
    "Makarna ve Mantı",
    "Makarna Sosları",
    "Konserve",
    "Salça",
    "Hazır Yemek ve Meze",
    "Margarin",
    "Ketçap",
    "Mayonez",
    "Hardal",
    "Çorba",
    "Tuz, Baharat",
    "Harç",
    "Bulyon",
    "Balık Konservesi",
    "Salata Sosu",
    "Soya ve Diğer Soslar",
    "Hamur ve Pasta Malzemeleri",
    "Turşu",
    "Diğer",
  ],
  "Diğer": [
    "Diğer",
  ]
};
